// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxxr5EXy-88nZILiGJnG6BsqFz3l2pEPo',
    appId: '1:231386436060:web:47ffbd56d5a68f622bff19',
    messagingSenderId: '231386436060',
    projectId: 'georura',
    authDomain: 'georura.firebaseapp.com',
    storageBucket: 'georura.firebasestorage.app',
    measurementId: 'G-0Y1EVJ0ZZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWyoRDxJp0sVfBi5NTkPZgNm2akLwTtKg',
    appId: '1:231386436060:android:713a3b73a91126262bff19',
    messagingSenderId: '231386436060',
    projectId: 'georura',
    storageBucket: 'georura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMlwILqoMZsPIeu7Raqjf32zjBi41rlrc',
    appId: '1:231386436060:ios:bee728e5d72a5d2c2bff19',
    messagingSenderId: '231386436060',
    projectId: 'georura',
    storageBucket: 'georura.firebasestorage.app',
    iosClientId: '231386436060-6lk3dmtte9f38arj3rnek34h77eou6ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruralmap',
  );
}
